plugins {
    id 'com.android.application'
}

android {
    namespace 'com.thirdlib.app'
    compileSdk rootProject.ext.compileSdk

    defaultConfig {
        applicationId "com.thirdlib.app"
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation project(':lib')
}
