plugins {
    id 'com.android.application'
}

android {
    namespace 'com.thirdlib.app'
    compileSdk rootProject.ext.compileSdk

    defaultConfig {
        applicationId "com.thirdlib.app"
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk
        ndkVersion rootProject.ext.ndkVersion

        ndk {
            abiFilters 'arm64-v8a'
        }

        externalNativeBuild {
            cmake {
                cppFlags '-v'
                arguments "-DANDROID_STL=c++_shared"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        prefab true
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }
}

repositories {
    maven {
        url = uri("${rootDir}/../local-maven-repo")
    }
}

dependencies {
    // 引入thirdpartylib包（包含thirdpartylib和zlib两个prefab模块）
    implementation 'com.thirdlib:thirdpartylib:1.0.0'
}
