plugins {
    id 'com.android.application'
}

android {
    namespace 'com.thirdlib.app'
    compileSdk rootProject.ext.compileSdk

    defaultConfig {
        applicationId "com.thirdlib.app"
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk
        ndkVersion rootProject.ext.ndkVersion

        ndk {
            abiFilters 'arm64-v8a'
            //abiFilters 'armeabi-v7a'
        }

        externalNativeBuild {
            cmake {
                cppFlags '-v', '-DSPDLOG_FMT_EXTERNAL', '-DFMT_HEADER_ONLY'
                arguments "-DANDROID_STL=c++_shared"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        prefab true
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }
}

dependencies {
    // 引入thirdpartylib包（包含thirdpartylib、zlib、minizip、bzip2等prefab模块）
    implementation 'com.thirdlib:thirdpartylib:1.0.0'
    implementation 'com.thirdlib:mycurl:1.0.0'

    // RecyclerView
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
}
