plugins {
    id 'com.android.library'
    id 'maven-publish'
    id 'com.thirdlib.prefab'
}

android {
    namespace 'com.thirdlib.mycurl'
    compileSdk rootProject.ext.compileSdk

    defaultConfig {
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk
        ndkVersion rootProject.ext.ndkVersion

        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a'
        }

        externalNativeBuild {
            cmake {
                cppFlags '-v'
                arguments "-DANDROID_STL=c++_shared"
            }
            experimentalProperties.put("prefab.mycurl.exportLibraries", ["thirdpartylib::curl"])
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    buildFeatures {
        prefab true
        prefabPublishing true
    }

    prefab {
        mycurl {
            headers = "src/main/cpp"
            libraryName = "libmycurl"
        }
    }

    externalNativeBuild {
        cmake {
            path 'CMakeLists.txt'
            version '3.22.1'
        }
    }

    publishing {
        singleVariant("release")
    }
}

dependencies {
    // mycurl 编译时使用 lib 的 Prefab 获取 curl
    implementation 'com.thirdlib:thirdpartylib:1.0.0'
}

// Maven 发布配置
apply from: 'mycurl-publish.gradle'

// 场景2：清理传递依赖的 .so
conanPrefab {
    libraryName = 'mycurl'

    // 场景控制
    injectConanPrefab = false     // 关闭场景1
    cleanTransitiveJniLibs = true  // 开启场景2
}
